In [4]:
from pycaret.nlp import *
import pandas as pd
import numpy as np
import spacy
import en_core_web_sm
import re 
import string

In [7]:
data = pd.read_csv('youtoxic_english_1000.csv')
data.head()

,CommentId,VideoId,Text,IsToxic,IsAbusive,IsThreat,IsProvocative,IsObscene,IsHatespeech,IsRacist,IsNationalist,IsSexist,IsHomophobic,IsReligiousHate,IsRadicalism
0,Ugg2KwwX0V8-aXgCoAEC,04kJtp6pVXI,If only people would just take a step back and...,False,False,False,False,False,False,False,False,False,False,False,False
1,Ugg2s5AzSPioEXgCoAEC,04kJtp6pVXI,Law enforcement is not trained to shoot to app...,True,True,False,False,False,False,False,False,False,False,False,False
2,Ugg3dWTOxryFfHgCoAEC,04kJtp6pVXI,\nDont you reckon them 'black lives matter' ba...,True,True,False,False,True,False,False,False,False,False,False,False
3,Ugg7Gd006w1MPngCoAEC,04kJtp6pVXI,There are a very large number of people who do...,False,False,False,False,False,False,False,False,False,False,False,False
4,Ugg8FfTbbNF8IngCoAEC,04kJtp6pVXI,"The Arab dude is absolutely right, he should h...",False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
text = data['Text']
def Limpieza (text):
    
    
    text = text.lower() 
    text = re.sub('\[.*?\]', '', text) 
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text) 
    text = re.sub('\w*\d\w*', '', text) 
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    
    text = text.lower() 
    text = re.sub('\[.*?\]', '', text) 
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text) 
    text = re.sub('\w*\d\w*', '', text) 
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
        

    round1 = lambda x: clean_text_round1(x) 

    text.replace(u'\xa0', u' ')
    text_clean = text
    

    # Limpiamos emojis

    def remove_emojis(text_clean):
        emoj = re.compile("["
            u"\U0001F600-\U0001F64F"  # emoticons
            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
            u"\U0001F680-\U0001F6FF"  # transport & map symbols
            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
            u"\U00002500-\U00002BEF"  # chinese char
            u"\U00002702-\U000027B0"
            u"\U00002702-\U000027B0"
            u"\U000024C2-\U0001F251"
            u"\U0001f926-\U0001f937"
            u"\U00010000-\U0010ffff"
            u"\u2640-\u2642" 
            u"\u2600-\u2B55"
            u"\u200d"
            u"\u23cf"
            u"\u23e9"
            u"\u231a"
            u"\ufe0f"  # dingbats
            u"\u3030"
                        "]+", re.UNICODE)
        return re.sub(emoj, '', text_clean)



    nlp = spacy.load("en_core_web_sm")
    text_clean = text_clean.apply(lambda x: nlp.tokenizer(x))

    return text_clean

NameError: name 'text_clean' is not defined

In [5]:
data['Text'] = data['Text'].replace(u'\xa0', u' ')

In [6]:
text_clean = data["Text"].apply(round1)
text_clean

0      if only people would just take a step back and...
1      law enforcement is not trained to shoot to app...
2      dont you reckon them black lives matter banner...
3      there are a very large number of people who do...
4      the arab dude is absolutely right he should ha...
                             ...
995    i remember that they sent in the national defe...
996    stats dont represent the problem race baiting ...
997    the quote from the mother wow that hit hard ve...
998                              this video is so racist
999          god the narrator has such an annoying lisp
Name: Text, Length: 1000, dtype: object

In [7]:
# Limpiamos emojis
import re
def remove_emojis(data_clean):
    emoj = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    return re.sub(emoj, '', data_clean)

In [8]:
final_text = text_clean.apply(remove_emojis)
final_text

0      if only people would just take a step back and...
1      law enforcement is not trained to shoot to app...
2      dont you reckon them black lives matter banner...
3      there are a very large number of people who do...
4      the arab dude is absolutely right he should ha...
                             ...
995    i remember that they sent in the national defe...
996    stats dont represent the problem race baiting ...
997    the quote from the mother wow that hit hard ve...
998                              this video is so racist
999          god the narrator has such an annoying lisp
Name: Text, Length: 1000, dtype: object

In [9]:
istoxic = data["IsToxic"].astype("uint8")
result = pd.concat([final_text, istoxic], axis=1)
result

                                                  Text  IsToxic
0    if only people would just take a step back and...        0
1    law enforcement is not trained to shoot to app...        1
2    dont you reckon them black lives matter banner...        1
3    there are a very large number of people who do...        0
4    the arab dude is absolutely right he should ha...        0
..                                                 ...      ...
995  i remember that they sent in the national defe...        0
996  stats dont represent the problem race baiting ...        1
997  the quote from the mother wow that hit hard ve...        0
998                            this video is so racist        0
999        god the narrator has such an annoying lisp         0

[1000 rows x 2 columns]

# AUTO ML

In [1]:
import spacy
import en_core_web_sm

In [11]:
nlp = spacy.load("en_core_web_sm")
result["tokenizacion"] = final_text.apply(lambda x: nlp.tokenizer(x))
result

,Text,IsToxic,tokenizacion
0,if only people would just take a step back and...,0,"(if, only, people, would, just, take, a, step,..."
1,law enforcement is not trained to shoot to app...,1,"(law, enforcement, is, not, trained, to, shoot..."
2,dont you reckon them black lives matter banner...,1,"(do, nt, you, reckon, them, black, lives, matt..."
3,there are a very large number of people who do...,0,"(there, are, a, very, large, number, of, peopl..."
4,the arab dude is absolutely right he should ha...,0,"(the, arab, dude, is, absolutely, right, he, s..."
...,...,...,...
995,i remember that they sent in the national defe...,0,"(i, remember, that, they, sent, in, the, natio..."
996,stats dont represent the problem race baiting ...,1,"(stats, do, nt, represent, the, problem, race,..."
997,the quote from the mother wow that hit hard ve...,0,"(the, quote, from, the, mother, wow, that, hit..."
998,this video is so racist,0,"(this, video, is, so, racist)"
999,god the narrator has such an annoying lisp,0,"(god, the, narrator, has, such, an, annoying, ..."

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
count_vect = CountVectorizer(stop_words='english')
transformer = TfidfTransformer(norm='l2',sublinear_tf=True)

In [13]:
X = result["tokenizacion"]
y = result["IsToxic"]

In [14]:
import re
import nltk
import gensim
from gensim.models import Word2Vec

In [15]:
from pycaret.nlp import *
pre_process = setup(data = result ,target = 'tokenizacion', session_id = 1, custom_stopwords= ['a', 'about', 'above', 'after', 'again', 'ain', 'all', 'am', 'an',
             'and','any','are', 'as', 'at', 'be', 'because', 'been', 'before',
             'being', 'below', 'between','both', 'by', 'can', 'd', 'did', 'do',
             'does', 'doing', 'down', 'during', 'each','few', 'for', 'from', 
             'further', 'had', 'has', 'have', 'having', 'he', 'her', 'here',
             'hers', 'herself', 'him', 'himself', 'his', 'how', 'i', 'if', 'in',
             'into','is', 'it', 'its', 'itself', 'just', 'll', 'm', 'ma',
             'me', 'more', 'most','my', 'myself', 'now', 'o', 'of', 'on', 'once',
             'only', 'or', 'other', 'our', 'ours','ourselves', 'out', 'own', 're',
             's', 'same', 'she', "shes", 'should', "shouldve",'so', 'some', 'such',
             't', 'than', 'that', "thatll", 'the', 'their', 'theirs', 'them',
             'themselves', 'then', 'there', 'these', 'they', 'this', 'those', 
             'through', 'to', 'too','under', 'until', 'up', 've', 'very', 'was',
             'we', 'were', 'what', 'when', 'where','which','while', 'who', 'whom',
             'why', 'will', 'with', 'won', 'y', 'you', "youd","youll", "youre",
             "youve", 'your', 'yours', 'yourself', 'yourselves'])

In [16]:
models()

                                  Name                  Reference
ID
lda        Latent Dirichlet Allocation     gensim/models/ldamodel
lsi           Latent Semantic Indexing     gensim/models/lsimodel
hdp     Hierarchical Dirichlet Process     gensim/models/hdpmodel
rp                  Random Projections      gensim/models/rpmodel
nmf  Non-Negative Matrix Factorization  sklearn.decomposition.NMF

In [17]:
lda = create_model('lda')
print(lda)

LdaModel<num_terms=3145, num_topics=4, decay=0.5, chunksize=100>

In [18]:
lda_data = assign_model(lda)
lda_data.head()

,Text,IsToxic,tokenizacion,Topic_0,Topic_1,Topic_2,Topic_3,Dominant_Topic,Perc_Dominant_Topic
0,if only people would just take a step back and...,0,people take step back make case people situati...,0.002746,0.022774,0.025466,0.949014,Topic 3,0.95
1,law enforcement is not trained to shoot to app...,1,law_enforcement train shoot apprehend train sh...,0.019532,0.035104,0.860591,0.084773,Topic 2,0.86
2,dont you reckon them black lives matter banner...,1,reckon black lives_matter banner hold white ki...,0.377479,0.015017,0.482867,0.124637,Topic 2,0.48
3,there are a very large number of people who do...,0,large number people police officer call crimin...,0.005985,0.011649,0.048873,0.933494,Topic 3,0.93
4,the arab dude is absolutely right he should ha...,0,arab dude absolutely right shot extra time sho...,0.013466,0.024463,0.747488,0.214584,Topic 2,0.75

In [19]:
from pycaret.classification import *

In [20]:
lda_data.drop(['Text','tokenizacion',], axis = 1, inplace=True, errors='ignore')

In [21]:
model = setup(data = lda_data, target = 'IsToxic')

In [22]:
compare_models(sort='Recall',n_select = 5)

[GaussianNB(priors=None, var_smoothing=1e-09),
 QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                               store_covariance=False, tol=0.0001),
 DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                        max_depth=None, max_features=None, max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_samples_leaf=1,
                        min_samples_split=2, min_weight_fraction_leaf=0.0,
                        random_state=410, splitter='best'),
 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                        criterion='gini', max_depth=None, max_features='sqrt',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0, min_samples_leaf=1,
                        min_samples_split=2, min_weight_fraction_leaf=0.0,
                        n_estimators=100, n_jobs=-1, oob_score=False,
                        random_state=410, verbose=0, warm_start=False),
 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                      metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                      weights='uniform')]

# Naive Bayes

In [23]:
naivebayes = create_model('nb',verbose = False)

In [24]:
tuned_naivebayes = tune_model(naivebayes, optimize = 'Recall', early_stopping = True)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [25]:
predict_model(naivebayes)

,Topic_0,Topic_1,Topic_2,Topic_3,Dominant_Topic_Topic 3,Dominant_Topic_Topic 1,Dominant_Topic_Topic 0,Dominant_Topic_Topic 2,Perc_Dominant_Topic,IsToxic,prediction_label,prediction_score
699,0.068565,0.121105,0.473491,0.336839,0.0,0.0,0.0,1.0,0.47,1,1,0.5558
700,0.220395,0.101836,0.416964,0.260805,0.0,0.0,0.0,1.0,0.42,1,0,0.6053
701,0.152891,0.319622,0.356862,0.170625,0.0,0.0,0.0,1.0,0.36,1,0,0.5582
702,0.024282,0.043070,0.722425,0.210223,0.0,0.0,0.0,1.0,0.72,1,1,0.7091
703,0.068564,0.121098,0.530666,0.279672,0.0,0.0,0.0,1.0,0.53,0,1,0.5848
...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.009134,0.535379,0.372242,0.083245,0.0,1.0,0.0,0.0,0.54,1,1,0.5472
996,0.009985,0.051944,0.176227,0.761844,1.0,0.0,0.0,0.0,0.76,0,1,0.7911
997,0.055938,0.099067,0.548116,0.296879,0.0,0.0,0.0,1.0,0.55,0,1,0.5997
998,0.426108,0.098804,0.248415,0.226673,0.0,0.0,1.0,0.0,0.43,1,0,0.9990
999,0.024744,0.045053,0.353832,0.576370,1.0,0.0,0.0,0.0,0.58,1,1,0.6732

In [30]:
np.abs(((0.8849 - 0.7703)/0.8849) *100)

12.950615888800998

# QDA

In [26]:
qda = create_model('qda',verbose = False)

In [27]:
tuned_qda = tune_model(qda, optimize = 'Recall', early_stopping = False)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [28]:
predict_model(qda)

,Topic_0,Topic_1,Topic_2,Topic_3,Dominant_Topic_Topic 3,Dominant_Topic_Topic 1,Dominant_Topic_Topic 0,Dominant_Topic_Topic 2,Perc_Dominant_Topic,IsToxic,prediction_label,prediction_score
699,0.068565,0.121105,0.473491,0.336839,0.0,0.0,0.0,1.0,0.47,1,1,0.6398
700,0.220395,0.101836,0.416964,0.260805,0.0,0.0,0.0,1.0,0.42,1,1,0.5142
701,0.152891,0.319622,0.356862,0.170625,0.0,0.0,0.0,1.0,0.36,1,0,0.9894
702,0.024282,0.043070,0.722425,0.210223,0.0,0.0,0.0,1.0,0.72,1,1,0.8071
703,0.068564,0.121098,0.530666,0.279672,0.0,0.0,0.0,1.0,0.53,0,1,0.7365
...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.009134,0.535379,0.372242,0.083245,0.0,1.0,0.0,0.0,0.54,1,0,0.5754
996,0.009985,0.051944,0.176227,0.761844,1.0,0.0,0.0,0.0,0.76,0,1,0.9842
997,0.055938,0.099067,0.548116,0.296879,0.0,0.0,0.0,1.0,0.55,0,1,0.7064
998,0.426108,0.098804,0.248415,0.226673,0.0,0.0,1.0,0.0,0.43,1,0,0.9961
999,0.024744,0.045053,0.353832,0.576370,1.0,0.0,0.0,0.0,0.58,1,1,0.7968

In [29]:

np.abs(((0.9640 - 0.9508)/0.9640) *100)

1.3692946058091275